# Bangla Digit Classification
Dataset provided by MD. Arif

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv("data.csv")
df.head()

Label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0      8  251  252    1  247  249  254  255  255  255  ...    255    255   
1      2  255  255  255  255  255  255  255  255  255  ...    255    252   
2      9  255  255  255  255  254  255  250  253  253  ...    255    255   
3      0  255  254  255  255  255  255  254  254  254  ...     31    244   
4      0  255  255  255  255  255  254  254  254  255  ...    254    253   

   28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0    255    255    255    255    255    255    255    255  
1    254    255    254      6      0    239    253    255  
2    255    255    255    255    255    255    255    255  
3    255    255    255    251    254    254    254    255  
4    254    253    253    254    254    254    255    255  

[5 rows x 785 columns]

1. Create features and target array.
2. Scale features array.
3. Split dataset in training and test set with ratio of 0.3

In [3]:
X = df.drop("Label", axis=1).values
y = df["Label"].values

## I'm using two kind of scaling
* sklearn.preprocessing.StandardScaler (using variable std_X)
* Simply dividing all values by 255. This will make the range of data [0,1]

In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
std_X = sc.fit_transform(X)
std_X

array([[ -0.11464388,  -0.02393645, -12.80894999, ...,   0.40316392,
          0.39639535,   0.33062486],
       [  0.11864656,   0.12658178,   0.13324576, ...,   0.19812513,
          0.37104972,   0.33062486],
       [  0.11864656,   0.12658178,   0.13324576, ...,   0.40316392,
          0.39639535,   0.33062486],
       ...,
       [ -0.05632127,  -0.02393645,   0.13324576, ...,   0.40316392,
          0.39639535,   0.33062486],
       [  0.11864656,   0.12658178,   0.13324576, ...,   0.37753408,
          0.39639535,   0.33062486],
       [  0.11864656,   0.12658178,   0.13324576, ...,   0.40316392,
          0.39639535,   0.33062486]])

In [5]:
X = X / 255
X
# try minMaxScaler

array([[0.98431373, 0.98823529, 0.00392157, ..., 1.        , 1.        ,
        1.        ],
       [1.        , 1.        , 1.        , ..., 0.9372549 , 0.99215686,
        1.        ],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       ...,
       [0.98823529, 0.98823529, 1.        , ..., 1.        , 1.        ,
        1.        ],
       [1.        , 1.        , 1.        , ..., 0.99215686, 1.        ,
        1.        ],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ]])

In [6]:
X.min(), X.max()

(0.0, 1.0)

## Spliting the dataset using train_test_split

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
std_X_train, std_X_test, std_y_train, std_y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Stochastic Gradient Descent


In [8]:
from sklearn.linear_model import SGDClassifier
sgd_clf_1 = SGDClassifier(random_state=42)
sgd_clf_2 = SGDClassifier(random_state=42)

sgd_clf_1.fit(X_train, y_train)
sgd_clf_2.fit(std_X_train, std_y_train)

y_pred = sgd_clf_1.predict(X_test)
std_y_pred = sgd_clf_1.predict(std_X_test)

n_correct = sum(y_pred == y_test)
std_n_correct = sum(std_y_pred == std_y_test)

print(n_correct, std_n_correct)

3897 3897


In [9]:
print(n_correct/len(y_pred), std_n_correct/len(std_y_pred))

0.8316261203585147 0.8316261203585147


## Using cross validation and KFold

In [11]:
from sklearn.model_selection import cross_val_score, KFold

sgd_clf_3 = SGDClassifier(random_state=42)
sgd_clf_4 = SGDClassifier(random_state=42)

kf = KFold(n_splits=6, shuffle=True, random_state=42)
cv_1 = cross_val_score(sgd_clf_3, X_train, y_train, cv=kf)
cv_2 = cross_val_score(sgd_clf_4, std_X_train, std_y_train, cv=kf)
print(cv_1, cv_2)

[0.82062534 0.80526604 0.80186608 0.76838639 0.82327113 0.8079034 ] [0.82062534 0.80526604 0.80186608 0.76838639 0.82327113 0.8079034 ]


### StandarScaler and hard coded scaling perform same. We'll use hard coded scaler from now on.

In [13]:
# Experiment with different n_splits value
sgd_clf_5 = SGDClassifier(random_state=42)
kf_2 = KFold(n_splits=3, shuffle=True, random_state=42)
cv_3 = cross_val_score(sgd_clf_5, X_train, y_train, cv=kf_2)
cv_3

array([0.82057613, 0.80329218, 0.8183315 ])

In [14]:
kf_3 = KFold(n_splits=5, shuffle=True, random_state=42)
cv_4 = cross_val_score(sgd_clf_5, X_train, y_train, cv=kf_3)
cv_4

array([0.81801555, 0.81115684, 0.80749886, 0.82898948, 0.83760293])

## Confusion matrix

In [15]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred) # predictions are from sgd_clf_1

array([[441,   8,   7,   4,   0,   5,  12,   5,   5,  12],
       [  6, 386,   6,   6,   0,   9,   7,   1,   7,  37],
       [  7,   5, 424,   3,  10,   7,   6,   4,   6,  10],
       [  6,   3,   7, 396,   0,   6,  48,   1,   4,  19],
       [  6,   6,   9,   3, 355,  16,   9,   4,   5,   7],
       [  6,   5,  13,   7,   5, 356,  63,   7,  10,   8],
       [  3,   2,   8,  33,   1,  10, 374,   2,   9,  14],
       [  1,   0,  13,   5,   3,  10,   7, 382,   2,  13],
       [  5,   1,  10,   3,   2,   5,  12,   0, 422,  10],
       [  6,  43,  19,  11,   6,   4,  15,   5,  18, 361]], dtype=int64)

## Precision and Recall

In [18]:
from sklearn.metrics import precision_score, recall_score

precision = precision_score(y_test, y_pred,average=None)
recall = recall_score(y_test, y_pred,average=None)

print(precision, recall)

[0.90554415 0.84095861 0.82170543 0.84076433 0.92931937 0.8317757
 0.67631103 0.92944039 0.8647541  0.73523422] [0.88376754 0.83010753 0.87966805 0.80816327 0.8452381  0.74166667
 0.82017544 0.87614679 0.89787234 0.7397541 ]
